plugins {
    id 'com.android.application'
}

android {
    namespace 'id.badutstore.kalkulator'
    compileSdk 35

    defaultConfig {
        applicationId 'id.badutstore.kalkulator'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            minifyEnabled false
        }
    }
}
